### ISSUE TITLE
Not working in Ionic4

### ISSUE THREAD

**Issue by stefdelec** [BatchLabs/Batch-Cordova-Plugin#19]
We have tried to implement in an ionic4 project, and it seems to not be working.

I created a blank project in cordova and another one in ionic4.

It compiles properly. In both projets, I see the log about my InstallationId. I copy this id, then go in dashboard=> send test notification to this installation id. My device is not receiving notification it on Ionic4. No popup, no error. 

It is working in cordova.

We create a

-  blank cordova project => OK

- blank ionic 4 project => KO

I created a private repo for these 2 projects if you want.

**Comment by abarisain** [comment]
Hello,

This plugin targets Cordova and not Ionic.

Ionic makes some tweaks and generally works differently. They're a cordova based solution, meaning that they're the ones that should not break compatibility. From the internal ticket you opened, it looks like their build system isn't merging the manifest properly (or is skipping the plugin's java source files)

That said, I know that some users have used Batch with Ionic successfully. Not sure what's happening in your case.
Could you compare what the backing cordova (and especially cordova-android) versions are?

Please note that since Ionic is moving away from cordova plugins, they might not be interested in looking at the issue

**Comment by stefdelec** [comment]
I made a PR that fix prob in ionic4.
https://github.com/BatchLabs/cordova-plugin/pull/20/files

I havn't tested regression

**Comment by abarisain** [comment]
Hello,

Thanks for your report.

This should be fixed in the 3.0.0-beta.1 version of the plugin, which brings compatibility with Ionic and Ionic Capacitor.
